### ISSUE TITLE
Decoding error: Cannot read file at utils/scoring/wer_per_spk_details.pl line 135

### ISSUE THREAD

**Issue by maxwellzh** [thu-spmi/CAT#66]
> @liubin3702 
已经完成了完整的训练并且测试了在解码之前的字错误率。我现在遇到的问题是，在步骤8 TLG解码测试时，执行ctc-crf/decode.sh  遇到了“run.pl: job failed, log is in exp/TDNN_LSTM/decode_test/scoring_kaldi/log/stats1.log”的报错，log中没用error，只有一行“Cannot read file at utils/scoring/wer_per_spk_details.pl line 135.”疑似错误，无法定位到问题在哪里；能否帮忙看看可能是哪里出的问题？

_Originally posted by @liubin3702 in https://github.com/thu-spmi/CAT/issues/64#issuecomment-1296865057_

**Comment by maxwellzh** [comment]
@liubin3702 
我查看了一下这个脚本，是因为读取utt2spk文件出错导致的错误，请确认一下解码数据集下该文件是否正常

**Comment by liubin3702** [comment]
> @liubin3702 我查看了一下这个脚本，是因为读取utt2spk文件出错导致的错误，请确认一下解码数据集下该文件是否正常

该工具目前有没有流式识别的功能呢？

**Comment by maxwellzh** [comment]
如果是指从前端音频录入到识别结果流式输出，目前是不支持的。

如果指的是流式模型的训练，可以参考我们近期 INTERSPEECH2022 投稿的工作
[CUSIDE: Chunking, Simulating Future Context and Decoding for Streaming ASR](https://arxiv.org/abs/2203.16758)
有关代码在整理中，将于近期发布到当前项目。

**Comment by liubin3702** [comment]
> 如果是指从前端音频录入到识别结果流式输出，目前是不支持的。
> 
> 如果指的是流式模型的训练，可以参考我们近期 INTERSPEECH2022 投稿的工作 [CUSIDE: Chunking, Simulating Future Context and Decoding for Streaming ASR](https://arxiv.org/abs/2203.16758) 有关代码在整理中，将于近期发布到当前项目。

你好，CAT第二版工具对我目前的工作较有帮助，最近我想替换kaldi的特征，自定义了一个数据读取函数，使用自己写的特征提取，打算在线提取特征并就扩增，但在dataloader加载过程中遇到了 AttributeError: Can't pickle local object 'CDLL.__init__.<locals>._FuncPtr' 这个错误，一直无法解决，请问有没有遇到过？

**Comment by maxwellzh** [comment]
@liubin3702 能否发一下你使用的dataset的实现代码？

**Comment by liubin3702** [comment]
> 
**这个是dataset代码：**
class SpeechDatasetRebuild(Dataset):
    def __init__(self, data_path):
        self.backsound = []
        self.dataset = []
        self.enhance = Enhance_audio()
        self.Feats = Features(so_path='/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/featurizer/libfbanks.so')
        with open('/workspace/robin/work/DCN1.3_MASR/datasets/train/norder.train', 'r', encoding='utf-8') as f1:
            lines = f1.readlines()
            for line in lines:
                line = json.loads(line)
                self.backsound.append(line["audio_filepath"])#背景噪声

        with open(data_path,'r', encoding='utf-8') as f:
            for line in f:
                self.dataset.append([line.split('\t')[0],line.split('\t')[1],line.split('\t')[2]])#加载数据，每一行为音频地址、标签、weight
        print ('SpeechDatasetRebuild 初始化完成')
    def __len__(self):
        return len(self.dataset)
    def __getitem__(self, idx):
        audio_path, label, weight = self.dataset[idx]
        audios, sample_rate = soundfile.read(audio_path, dtype='float32')
        fbank_feat= self.Feats.get_fbanks(audios,64) # length*64
        return fbank_feat, torch.IntTensor(label), torch.tensor(weight, dtype=torch.float)

另外 在train里面  我将**Dataset = DataSet.SpeechDatasetPickle** 更改为 **Dataset = DataSet.SpeechDatasetRebuild** （自定义函数）
并将我训练数据和验证数据路径传入args 。

**具体报错如下：**
Traceback (most recent call last):
  File "ctc-crf/train1.py", line 211, in <module>
    main_spawner(args, main_worker)
  File "ctc-crf/train1.py", line 40, in main_spawner
    mp.spawn(_main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/workspace/data/robinliu/CAT-master2/egs/keyword3/ctc-crf/train1.py", line 112, in main_worker
    manager.run(train_sampler, trainloader, testloader, args)
  File "/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/coreutils.py", line 80, in run
    train(trainloader, epoch, args, self)
  File "/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/coreutils.py", line 373, in train
    for i, minibatch in enumerate(trainloader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 384, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1048, in __init__
    w.start()
  File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/conda/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'CDLL.__init__.<locals>._FuncPtr'

**Comment by liubin3702** [comment]
> @liubin3702 能否发一下你使用的dataset的实现代码？
**这个是dataset代码**：
`class SpeechDatasetRebuild(Dataset):
def init(self, data_path):
self.backsound = []
self.dataset = []
self.enhance = Enhance_audio()
self.Feats = Features(so_path='/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/featurizer/libfbanks.so')
with open('/workspace/robin/work/DCN1.3_MASR/datasets/train/norder.train', 'r', encoding='utf-8') as f1:
lines = f1.readlines()
for line in lines:
line = json.loads(line)
self.backsound.append(line["audio_filepath"])#背景噪声

    with open(data_path,'r', encoding='utf-8') as f:
        for line in f:
            self.dataset.append([line.split('\t')[0],line.split('\t')[1],line.split('\t')[2]])#加载数据，每一行为音频地址、标签、weight
    print ('SpeechDatasetRebuild 初始化完成')
def __len__(self):
    return len(self.dataset)
def __getitem__(self, idx):
    audio_path, label, weight = self.dataset[idx]
    audios, sample_rate = soundfile.read(audio_path, dtype='float32')
    fbank_feat= self.Feats.get_fbanks(audios,64) # length*64
    return fbank_feat, torch.IntTensor(label), torch.tensor(weight, dtype=torch.float)`

**Comment by liubin3702** [comment]
> @liubin3702 能否发一下你使用的dataset的实现代码？

这个是dataset代码：
`class SpeechDatasetRebuild(Dataset):
    def init(self, data_path):
        self.backsound = []
        self.dataset = []
        self.enhance = Enhance_audio()
        self.Feats = Features(so_path='/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/featurizer/libfbanks.so')
        with open('/workspace/robin/work/DCN1.3_MASR/datasets/train/norder.train', 'r', encoding='utf-8') as f1:
        lines = f1.readlines()
        for line in lines:
            line = json.loads(line)
            self.backsound.append(line["audio_filepath"])#背景噪声
    with open(data_path,'r', encoding='utf-8') as f:
        for line in f:
            self.dataset.append([line.split('\t')[0],line.split('\t')[1],line.split('\t')[2]])#加载数据，每一行为音频地址、标签、weight
    print ('SpeechDatasetRebuild 初始化完成')
    def __len__(self):
        return len(self.dataset)
    def __getitem__(self, idx):
        audio_path, label, weight = self.dataset[idx]
        audios, sample_rate = soundfile.read(audio_path, dtype='float32')
        fbank_feat= self.Feats.get_fbanks(audios,64) # length*64
        return fbank_feat, torch.IntTensor(label), torch.tensor(weight, dtype=torch.float)`

另外 在train里面 我将Dataset = DataSet.SpeechDatasetPickle 更改为 Dataset = DataSet.SpeechDatasetRebuild （自定义函数）
并将我训练数据和验证数据路径传入args 。

**具体报错如下：**
Traceback (most recent call last):
File "ctc-crf/train1.py", line 211, in
main_spawner(args, main_worker)
File "ctc-crf/train1.py", line 40, in main_spawner
mp.spawn(_main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
while not context.join():
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
fn(i, *args)
File "/workspace/data/robinliu/CAT-master2/egs/keyword3/ctc-crf/train1.py", line 112, in main_worker
manager.run(train_sampler, trainloader, testloader, args)
File "/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/coreutils.py", line 80, in run
train(trainloader, epoch, args, self)
File "/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/coreutils.py", line 373, in train
for i, minibatch in enumerate(trainloader):
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 438, in iter
return self._get_iterator()
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 384, in _get_iterator
return _MultiProcessingDataLoaderIter(self)
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1048, in init
w.start()
File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 112, in start
self._popen = self._Popen(self)
File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
return Popen(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in init
super().init(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 20, in init
self._launch(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
reduction.dump(process_obj, fp)
File "/opt/conda/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'CDLL.init.._FuncPtr'

**Comment by liubin3702** [comment]
> @liubin3702 能否发一下你使用的dataset的实现代码？

这个是dataset代码：
'''
class SpeechDatasetRebuild(Dataset):
    def init(self, data_path):
        self.backsound = []
        self.dataset = []
        self.enhance = Enhance_audio()
        self.Feats = Features(so_path='/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/featurizer/libfbanks.so')
        with open('/workspace/robin/work/DCN1.3_MASR/datasets/train/norder.train', 'r', encoding='utf-8') as f1:
        lines = f1.readlines()
        for line in lines:
            line = json.loads(line)
            self.backsound.append(line["audio_filepath"])#背景噪声
    with open(data_path,'r', encoding='utf-8') as f:
        for line in f:
            self.dataset.append([line.split('\t')[0],line.split('\t')[1],line.split('\t')[2]])#加载数据，每一行为音频地址、标签、weight
    print ('SpeechDatasetRebuild 初始化完成')
    def __len__(self):
        return len(self.dataset)
    def __getitem__(self, idx):
        audio_path, label, weight = self.dataset[idx]
        audios, sample_rate = soundfile.read(audio_path, dtype='float32')
        fbank_feat= self.Feats.get_fbanks(audios,64) # length*64
        return fbank_feat, torch.IntTensor(label), torch.tensor(weight, dtype=torch.float)
'''
另外 在train里面 我将Dataset = DataSet.SpeechDatasetPickle 更改为 Dataset = DataSet.SpeechDatasetRebuild （自定义函数）
并将我训练数据和验证数据路径传入args 。

具体报错如下：
Traceback (most recent call last):
File "ctc-crf/train1.py", line 211, in
main_spawner(args, main_worker)
File "ctc-crf/train1.py", line 40, in main_spawner
mp.spawn(_main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
while not context.join():
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
fn(i, *args)
File "/workspace/data/robinliu/CAT-master2/egs/keyword3/ctc-crf/train1.py", line 112, in main_worker
manager.run(train_sampler, trainloader, testloader, args)
File "/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/coreutils.py", line 80, in run
train(trainloader, epoch, args, self)
File "/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/coreutils.py", line 373, in train
for i, minibatch in enumerate(trainloader):
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 438, in iter
return self._get_iterator()
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 384, in _get_iterator
return _MultiProcessingDataLoaderIter(self)
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1048, in init
w.start()
File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 112, in start
self._popen = self._Popen(self)
File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
return Popen(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in init
super().init(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 20, in init
self._launch(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
reduction.dump(process_obj, fp)
File "/opt/conda/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'CDLL.init.._FuncPtr'

**Comment by liubin3702** [comment]
这个是dataset代码：
'''
class SpeechDatasetRebuild(Dataset):
    def init(self, data_path):
        self.backsound = []
        self.dataset = []
        self.enhance = Enhance_audio()
        self.Feats = Features(so_path='/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/featurizer/libfbanks.so')
        with open('/workspace/robin/work/DCN1.3_MASR/datasets/train/norder.train', 'r', encoding='utf-8') as f1:
            lines = f1.readlines()
            for line in lines:
                line = json.loads(line)
                self.backsound.append(line["audio_filepath"])#背景噪声
        with open(data_path,'r', encoding='utf-8') as f:
            for line in f:
                self.dataset.append([line.split('\t')[0],line.split('\t')[1],line.split('\t')[2]])#加载数据，每一行为音频地址、标签、weight
    print ('SpeechDatasetRebuild 初始化完成')
    def len(self):
        return len(self.dataset)
    def getitem(self, idx):
        audio_path, label, weight = self.dataset[idx]
        audios, sample_rate = soundfile.read(audio_path, dtype='float32')
        fbank_feat= self.Feats.get_fbanks(audios,64) # length*64
        return fbank_feat, torch.IntTensor(label), torch.tensor(weight, dtype=torch.float)
'''
另外 在train里面 我将Dataset = DataSet.SpeechDatasetPickle 更改为 Dataset = DataSet.SpeechDatasetRebuild （自定义函数）
并将我训练数据和验证数据路径传入args 。

具体报错如下：
Traceback (most recent call last):
File "ctc-crf/train1.py", line 211, in
main_spawner(args, main_worker)
File "ctc-crf/train1.py", line 40, in main_spawner
mp.spawn(_main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
while not context.join():
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
fn(i, *args)
File "/workspace/data/robinliu/CAT-master2/egs/keyword3/ctc-crf/train1.py", line 112, in main_worker
manager.run(train_sampler, trainloader, testloader, args)
File "/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/coreutils.py", line 80, in run
train(trainloader, epoch, args, self)
File "/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/coreutils.py", line 373, in train
for i, minibatch in enumerate(trainloader):
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 438, in iter
return self._get_iterator()
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 384, in _get_iterator
return _MultiProcessingDataLoaderIter(self)
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1048, in init
w.start()
File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 112, in start
self._popen = self._Popen(self)
File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
return Popen(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in init
super().init(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 20, in init
self._launch(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
reduction.dump(process_obj, fp)
File "/opt/conda/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'CDLL.init.._FuncPtr'

**Comment by liubin3702** [comment]
> 
这个是dataset代码：
`class SpeechDatasetRebuild(Dataset):
    def init(self, data_path):
        self.backsound = []
        self.dataset = []
        self.enhance = Enhance_audio()
        self.Feats = Features(so_path='/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/featurizer/libfbanks.so')
        with open('/workspace/robin/work/DCN1.3_MASR/datasets/train/norder.train', 'r', encoding='utf-8') as f1:
        lines = f1.readlines()
        for line in lines:
            line = json.loads(line)
            self.backsound.append(line["audio_filepath"])#背景噪声
    with open(data_path,'r', encoding='utf-8') as f:
        for line in f:
            self.dataset.append([line.split('\t')[0],line.split('\t')[1],line.split('\t')[2]])#加载数据，每一行为音频地址、标签、weight
    print ('SpeechDatasetRebuild 初始化完成')
    def __len__(self):
        return len(self.dataset)
    def __getitem__(self, idx):
        audio_path, label, weight = self.dataset[idx]
        audios, sample_rate = soundfile.read(audio_path, dtype='float32')
        fbank_feat= self.Feats.get_fbanks(audios,64) # length*64
        return fbank_feat, torch.IntTensor(label), torch.tensor(weight, dtype=torch.float)`
另外 在train里面 我将Dataset = DataSet.SpeechDatasetPickle 更改为 Dataset = DataSet.SpeechDatasetRebuild （自定义函数）
并将我训练数据和验证数据路径传入args 。

具体报错如下：
Traceback (most recent call last):
File "ctc-crf/train1.py", line 211, in
main_spawner(args, main_worker)
File "ctc-crf/train1.py", line 40, in main_spawner
mp.spawn(_main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
while not context.join():
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
fn(i, *args)
File "/workspace/data/robinliu/CAT-master2/egs/keyword3/ctc-crf/train1.py", line 112, in main_worker
manager.run(train_sampler, trainloader, testloader, args)
File "/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/coreutils.py", line 80, in run
train(trainloader, epoch, args, self)
File "/workspace/data/robinliu/CAT-master2/scripts/ctc-crf/coreutils.py", line 373, in train
for i, minibatch in enumerate(trainloader):
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 438, in iter
return self._get_iterator()
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 384, in _get_iterator
return _MultiProcessingDataLoaderIter(self)
File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1048, in init
w.start()
File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 112, in start
self._popen = self._Popen(self)
File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
return Popen(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in init
super().init(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 20, in init
self._launch(process_obj)
File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
reduction.dump(process_obj, fp)
File "/opt/conda/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'CDLL.init.._FuncPtr'

**Comment by maxwellzh** [comment]
你好，根据我的经验来看，dataloader 这个错误一般是dataset中初始化了一些特别的类型，而这些类型在多进程数据加载时无法被序列化fork到新进程就会报错。

要确认是否是该原因，你可以尝试手动设置datloader的num_workers=0来禁用多进程数据加载，如果设置0后就不报这个错误，可以证实该原因。

如果确认是这个原因，设置num_workers=0是一个不太好的解决方案，因为会导致数据加载变慢；
更好的方式是去修改初始化的方式，把无法pickle的类型放在getitem函数里初始化，在此之前你需要排查一下init函数里是哪个变量导致的问题

**Comment by liubin3702** [comment]
改为0后确实可以加载了  我根据你说的在优化优化
