### ISSUE TITLE
decode error

### ISSUE THREAD

**Issue by jasonyong** [thu-spmi/CAT#76]
hi, when I run the decode process, some error happens:

==================== Stage 4 Decode ====================
Decode: set 'inference:infer:option:resume' -> /home/test/hd1/work/CAT/egs/aishell/exp/char_ctc-crf-cuside/check/checkpoint.1e1000s.pt
Decode: set 'inference:infer:option:output_dir' -> exp/char_ctc-crf-cuside/decode/{}
Decode: test: set 'output_dir' -> exp/char_ctc-crf-cuside/decode/test
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
        Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
        Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
Traceback (most recent call last):
  File "/home/test/hd1/work/CAT/egs/aishell/utils/pipeline/asr.py", line 464, in <module>
    interface.main(parse_args_from_var(
  File "/home/test/hd1/work/CAT/cat/ctc/cal_logit.py", line 54, in main
    mp.spawn(worker, nprocs=world_size, args=(args, q, model))
  File "/home/test/miniconda3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/test/miniconda3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/test/miniconda3/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/test/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/test/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/test/miniconda3/lib/python3.10/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory

Can you figure out the problems? thanks

**Comment by maxwellzh** [comment]
This is probably a bug related to numpy version. Can you try

```
# upgrade the numpy to latest 
pip install -U numpy
# if upgrade doesn't work, try to install the specific version 
pip install numpy==1.23.1
```

**Comment by maxwellzh** [comment]
See also
https://github.com/pytorch/pytorch/issues/37377#issuecomment-629530272

Feel free to re-open this issue if you have any question.
